version: 0.0
os: windows
files:
  - source: \
    destination: c:\
hooks:
  BeforeInstall:
    - location: \beforeinstall.bat
      timeout: 500
  AfterInstall:
    - location: \afterinstall.sh
      timeout: 500
