version: 0.0
os: windows
files:
  - source: \
    destination: c:\temp_rek
hooks:
  BeforeInstall:
    - location: \beforeinstall.bat
      timeout: 500
  AfterInstall:
    - location: \afterinstall.bat
      timeout: 500
